{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5551ad95",
   "metadata": {},
   "source": [
    "# Ques 1\n",
    "Q1. What is the purpose of the try statement?\n",
    "\n",
    "\n",
    "The purpose of the try statement in Python is to define a block of code in which exceptions may occur. It allows us to catch and handle exceptions that may be raised within the try block, preventing them from propagating up the call stack and causing the program to terminate abruptly.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4b84b103",
   "metadata": {},
   "source": [
    "# Ques 2\n",
    "Q2. What are the two most popular try statement variations?\n",
    "\n",
    "\n",
    "The two most popular try statement variations are:\n",
    "\n",
    "1. try-except: This variation allows you to specify one or more except blocks immediately after the try block. Each except block can catch and handle a specific type of exception. If an exception occurs within the try block, the corresponding except block with a matching exception type will be executed, allowing you to handle the exception gracefully.\n",
    "\n",
    "try:\n",
    "    # Code that may raise an exception\n",
    "\n",
    "\n",
    "except ExceptionType:\n",
    "    # Exception handling code\n",
    "    \n",
    "2. try-finally: This variation includes a finally block in addition to the try block. The code inside the finally block is always executed, whether an exception occurs or not. It is useful for performing cleanup operations or releasing resources that need to be done regardless of whether an exception is raised or caught.\n",
    "\n",
    "\n",
    "try:\n",
    "    # Code that may raise an exception\n",
    "\n",
    "\n",
    "finally:\n",
    "    # Cleanup code\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36235f30",
   "metadata": {},
   "source": [
    "# Ques 3\n",
    "\n",
    "Q3. What is the purpose of the raise statement?\n",
    "\n",
    "The raise statement in Python is used to explicitly raise an exception. It allows us to create and raise exceptions programmatically when certain conditions are met. The raise statement takes an exception type or an instance of an exception class as an argument and can optionally include an error message.\n",
    "\n",
    "if condition:\n",
    "    \n",
    "    raise ValueError(\"Invalid value\")\n",
    "    \n",
    "The purpose of the raise statement is to signal that an exceptional condition has occurred in your code and to propagate that exception to the appropriate exception handler or the top-level of your program.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f750089a",
   "metadata": {},
   "source": [
    "# Ques 4\n",
    "Q4. What does the assert statement do, and what other statement is it like?\n",
    "\n",
    "\n",
    "The assert statement in Python is used to check whether a given condition is true, and if it's not, it raises an AssertionError with an optional error message. It is primarily used for debugging and to ensure that certain assumptions about the state of the program are valid.\n",
    "\n",
    "The assert statement is similar to the if statement in terms of checking a condition, but it is primarily used for testing and debugging purposes. It is not meant to handle recoverable errors or exceptions. When running a Python script with the -O (optimize) flag or in a production environment, assert statements are typically ignored, and the condition checks are skipped for performance reasons.\n",
    "\n",
    "\n",
    "x = 10\n",
    "\n",
    "assert x > 0, \"x must be positive\"\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0bf04fb1",
   "metadata": {},
   "source": [
    "# Ques 5\n",
    "\n",
    "What is the purpose of the with/as argument, and what other statement is it like?\n",
    "\n",
    "The purpose of the with/as argument is to provide a convenient way to manage resources by creating a context within which the resources are automatically managed. It is used in conjunction with objects that implement the context management protocol, which define __enter__ and __exit__ methods.\n",
    "\n",
    "The with statement ensures that the __exit__ method of the context manager is always called, even if an exception occurs within the block. It helps with proper resource cleanup and exception handling.\n",
    "\n",
    "The with/as argument is similar to the try-finally statement, but it provides a more concise and readable way of managing resources. It automatically sets up the context, executes the code block, and then cleans up the resources, even if an exception occurs.\n",
    "\n",
    "\n",
    "with open('file.txt') as file:\n",
    "    # Code to read or write to the file\n",
    "\n",
    "\n",
    "In the example above, the open() function returns a file object that acts as a context manager. The with statement ensures that the file is properly closed after the block of code, regardless of whether an exception occurs or not.\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
